version: '3.8'

services:
  server:
    container_name: server
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_settings.conf:/etc/nginx/proxy_settings.conf:ro
      - ./nginx/cors_headers.conf:/etc/nginx/cors_headers.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      - api
      - front

  db:
    container_name: db
    image: mongo
    volumes:
      - mongo_data:/data/db

  api:
    container_name: api
    restart: always
    build: ./api

  front:
    container_name: front
    restart: always
    build: ./front

volumes:
  mongo_data: {}  # Correct way to declare a named volume
